/**
 * CustomManagerFormPage - prototype form rendered at /:partner/submit
 *
 * This page is fully open (no auth required). It is the destination for
 * partner-specific form URLs generated by the Custom Manager Form Builder.
 *
 * It is a UI-only proof-of-concept. No form data is submitted or stored.
 */
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Toast, useToast } from '../components/ui';
import { getPublicCustomForm } from '../utils/pilot2Api';

/** Turn a URL slug like "pure-gym" into "Pure Gym" */
function slugToLabel(slug) {
  return (slug || '')
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

const inputClass =
  'w-full h-10 rounded-lg border border-[var(--color-border-default)] bg-white px-3 text-sm text-[var(--color-text-primary)] placeholder-[var(--color-text-muted)] transition-[border-color,box-shadow] focus:border-[var(--color-brand-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--color-brand-primary)]/15';

const labelClass = 'mb-1.5 block text-sm font-medium text-[var(--color-text-primary)]';

export default function CustomManagerFormPage() {
  const { partner } = useParams();
  const { showToast } = useToast();
  const [config, setConfig] = useState(null);
  
  useEffect(() => {
    getPublicCustomForm(partner)
      .then((res) => {
        setConfig({
          partnerName: res.partnerName,
          logoDataUrl: res.logoDataUrl,
          fields: res.fields || [],
        });
      })
      .catch((err) => {
        console.error('Could not load public form', err);
      });
  }, [partner]);

  const partnerLabel = config?.partnerName || slugToLabel(partner);

  const handleSubmit = (e) => {
    e.preventDefault();
    showToast('Form submission is not available in this prototype.', 'success');
  };

  return (
    <div className="flex min-h-screen flex-col bg-[var(--color-surface-bg)] font-sans antialiased">
      <Toast />

      {/* Header */}
      <header className="shrink-0 border-b border-[var(--color-border-default)] bg-white">
        <div className="mx-auto flex h-14 max-w-[640px] items-center gap-3 px-4 sm:px-6">
          <img
            src="/image.png"
            alt=""
            className="h-6 w-auto shrink-0 object-contain"
          />
          <div className="min-w-0 border-l border-[var(--color-border-default)] pl-3">
            <p className="truncate text-sm font-semibold text-[var(--color-text-primary)]">
              Power Music
            </p>
            <p className="truncate text-[11px] text-[var(--color-text-secondary)]">
              {partnerLabel} Submission Form
            </p>
          </div>
          {/* Prototype badge */}
          <span className="ml-auto inline-flex shrink-0 items-center rounded-md bg-amber-50 px-2 py-0.5 text-[11px] font-semibold text-amber-700 ring-1 ring-inset ring-amber-200">
            Prototype
          </span>
        </div>
      </header>

      {/* Form card */}
      <main className="mx-auto w-full max-w-[480px] flex-1 px-4 py-10 sm:px-6">
        <div className="overflow-hidden rounded-2xl border border-[var(--color-border-default)] bg-white shadow-[var(--shadow-card)]">
          {/* Partner header */}
          <div className="bg-[var(--color-surface-panel)]/60 px-6 py-6 text-center border-b border-[var(--color-border-default)]">
            {config?.logoDataUrl ? (
              <img src={config.logoDataUrl} alt={partnerLabel} className="mx-auto mb-4 h-16 w-16 rounded-xl border border-[var(--color-border-default)] bg-white object-contain p-1.5" />
            ) : (
              <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-xl bg-[var(--color-brand-primary)]/10 text-lg font-bold text-[var(--color-brand-primary)] select-none">
                {(partnerLabel || 'P').charAt(0).toUpperCase()}
              </div>
            )}
            
            <h1 className="text-lg font-bold text-[var(--color-text-primary)]">
              {partnerLabel}
            </h1>
            <p className="mt-1 text-base font-bold text-[var(--color-text-primary)]">
              Submission Form
            </p>
            <p className="mt-1.5 text-sm text-[var(--color-text-secondary)]">
              Power Music admin has invited you to fill out this form.
            </p>
            <p className="mt-0.5 text-xs text-[var(--color-text-muted)]">
              Please provide the requested information below.
            </p>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-5 px-6 py-6">
            {config?.fields && config.fields.length > 0 ? (
              config.fields.map((field) => (
                <div key={field.id}>
                  <label htmlFor={`field-${field.id}`} className={labelClass}>
                    {field.name}
                  </label>
                  {field.type === 'Date' ? (
                    <input id={`field-${field.id}`} type="date" className={inputClass} required />
                  ) : field.type === 'Number' ? (
                    <input id={`field-${field.id}`} type="number" placeholder="0" className={inputClass} required />
                  ) : field.type === 'Email' ? (
                    <input id={`field-${field.id}`} type="email" placeholder="name@example.com" className={inputClass} required />
                  ) : field.type === 'Text and Number' ? (
                    <input id={`field-${field.id}`} type="text" inputMode="text" className={inputClass} required />
                  ) : (
                    <input id={`field-${field.id}`} type="text" className={inputClass} required />
                  )}
                </div>
              ))
            ) : (
              <div className="text-center text-sm text-[var(--color-text-secondary)]">
                No custom fields have been configured for this partner yet.
              </div>
            )}

            <button
              type="submit"
              className="mt-2 flex h-10 w-full items-center justify-center rounded-lg bg-[var(--color-brand-primary)] px-6 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-[var(--color-surface-sidebar-hover)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-brand-primary)]/35 focus-visible:ring-offset-1"
            >
              Submit
            </button>
          </form>

          {/* Prototype notice */}
          <div className="border-t border-[var(--color-border-default)] bg-amber-50/50 px-6 py-3 text-center">
            <p className="text-[11px] text-amber-700">
              This is a prototype preview. Form submission is not functional.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
